### PR TITLE
Puts the PugBot into Docker for easy deployment

### PR DESCRIPTION
**Pull request by jadametz**
Thanks for creating an awesome bot! My guild gets a lot of use out of it. We noticed that it stopped working a few weeks back so I wanted to get it running either on my laptop or up on a server. I'm a huge fan of Docker so for me, that was step one.

Let me know if you have any questions 😄

### CODE REVIEW

**Comment by reznok** [comment]
I love this, it's amazing, but I don't want to put it into the master branch. Mainly because anyone unfamiliar with docker (which somehow is still a lot of people...) will see it as too much of an entry barrier for the base project. I'll add to the README a link to your repo for anyone who is interested in setting it up in a docker container.

EDIT: Actually screw it, it looks like it could be used with or without docker this way. Going to test that to make sure, then probably do the merge. Thanks for contributing!

**Comment by reznok** [comment]
Is there any reason you moved the config options to pug.py? It's hard to see because this bot only has one command, but my intended file structure for that was each !<command> having its own script, creating a module style functionality. Putting the Discord config in there seems odd to me.

**Comment by jadametz** [comment]
Ah, was actually just trying to centralize some place for the config to come from. This was intended to make it a little easier to grab the values either from the file or the `ENV` in the case of Docker.

EDIT: Taking another look at the file structure with what you said in mind, I could refactor this back to the previous state where the only place `config` is loaded is in `pugbot.py` and then passed down to "modules." Thoughts on that approach?

**Comment by reznok** [comment]
That should do the trick.

**Comment by jadametz** [comment]
Cool, I'll try and work on this sometime in the next couple of days.

**Comment by jadametz** [comment]
@reznok submitted that refactor we were discussing. Let me know what you think.

**Pull request merged**
