### PR TITLE
Adds support for Nighthold and cleans up raid progression construction

### PR DESCRIPTION
**Pull request by jadametz**

### CODE REVIEW

**Comment by jadametz** [comment]
Glad you're enjoying the update, @kaitho!



As of now the raid progression does look in order to me...I see what you're saying though about it being a bit hidden in the middle of the overall output though. I'll look into cleaning this up a bit sometime this week/end.

**Comment by kaitho** [comment]
Okey, great @jadametz 

pugbot

Here it how it looks here, been looking at the code, but limited knowledge in that field.

**Comment by GuyonWoW** [comment]
Any chance to see the Artifact Level and Knowledge too?

Great tool btw

**Comment by jadametz** [comment]
@Thomas-SK doesn't look like AL or AK are available via the Blizzard API (unless I missed it somewhere).

**Comment by reznok** [comment]
Just saw this PR. Going to review the code and most likely add this in. Thanks for contributing!

**Pull request merged**
